// src/components/AlbumGallery.tsx
import { useMemo, useRef } from 'react'
import Box from '@mui/material/Box'
import AlbumIcon from '@mui/icons-material/Album'
import { Link } from '@tanstack/react-router'
import { useVirtualizer } from '@tanstack/react-virtual'
import { useTranslation } from 'react-i18next'

import { CoverImg } from '@/components/CoverImg'
import { useVirtualListHost } from '@/hooks/useVirtualListHost'
import {
  ALBUM_GALLERY_GAP_PX,
  albumGalleryColumns,
  albumGalleryRowHeight,
  chunkIntoRows,
} from '@/lib/albumGalleryLayout'
import { localizeAlbumName } from '@/lib/catalog/displayLabels'
import { capVirtualListHeight, virtualListNeedsScroll } from '@/lib/virtualListHeight'

export type AlbumGalleryTile = {
  name: string
  trackCount: number
  coverSrc?: string
}

export type AlbumGalleryProps = {
  tiles: AlbumGalleryTile[]
  /** Build the router `to` for a tile name. */
  pathFor: (name: string) => string
}

export function AlbumGallery({ tiles, pathFor }: AlbumGalleryProps) {
  const { t } = useTranslation()
  const { listHostRef, hostHeight, hostWidth } = useVirtualListHost({ observeWidth: true })
  const scrollParentRef = useRef<HTMLDivElement | null>(null)

  const columns = albumGalleryColumns(hostWidth)
  const albumRows = useMemo(
    () =>
      chunkIntoRows(tiles, columns).map((rowTiles, index) => ({
        key: `row-${index}-${rowTiles[0]?.name ?? index}`,
        tiles: rowTiles,
      })),
    [tiles, columns],
  )
  const rowHeight = albumGalleryRowHeight(hostWidth, columns)
  const listHeight = capVirtualListHeight(albumRows.length, rowHeight, hostHeight)
  const listFlush = !virtualListNeedsScroll(albumRows.length, rowHeight, hostHeight)

  const rowVirtualizer = useVirtualizer({
    count: albumRows.length,
    getScrollElement: () => scrollParentRef.current,
    estimateSize: () => rowHeight,
    overscan: 4,
  })

  const rowStyle = {
    gap: `${ALBUM_GALLERY_GAP_PX}px`,
    gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`,
    paddingBottom: `${ALBUM_GALLERY_GAP_PX}px`,
  } as const

  return (
    <Box
      ref={listHostRef}
      className="list-host album-gallery"
      sx={{ flex: '1 1 auto', minHeight: 0 }}
    >
      <Box
        ref={scrollParentRef}
        className={`album-list${listFlush ? ' album-list--flush' : ''}`}
        sx={{
          height: listHeight,
          overflowY: listFlush ? 'hidden' : 'auto',
          bgcolor: 'transparent',
          position: 'relative',
        }}
      >
        <Box sx={{ height: rowVirtualizer.getTotalSize(), width: '100%', position: 'relative' }}>
          {rowVirtualizer.getVirtualItems().map((virtualRow) => {
            const row = albumRows[virtualRow.index]
            if (!row) return null
            return (
              <Box
                key={row.key}
                className="album-gallery-row"
                style={{
                  ...rowStyle,
                  position: 'absolute',
                  top: 0,
                  left: 0,
                  width: '100%',
                  height: `${virtualRow.size}px`,
                  transform: `translateY(${virtualRow.start}px)`,
                  display: 'grid',
                  boxSizing: 'border-box',
                }}
              >
                {row.tiles.map((tile) => (
                  <Box
                    key={tile.name}
                    component={Link}
                    to={pathFor(tile.name)}
                    className="album-tile"
                    sx={{
                      color: 'inherit',
                      textDecoration: 'none',
                      animation: 'td-album-rise 0.45s ease both',
                      minWidth: 0,
                      '@media (prefers-reduced-motion: reduce)': {
                        animation: 'none',
                      },
                      '&:hover .album-tile__art': {
                        transform: 'translateY(calc(var(--td-motion-cover) * -1))',
                      },
                    }}
                  >
                    <Box
                      className="album-tile__art"
                      sx={{
                        aspectRatio: '1',
                        borderRadius: 'var(--td-radius-lg)',
                        overflow: 'hidden',
                        boxShadow: 'var(--td-cover-shadow)',
                        transition: 'transform 0.2s ease',
                      }}
                    >
                      {tile.coverSrc ? (
                        <CoverImg
                          src={tile.coverSrc}
                          aspectRatio={1}
                          className="album-tile__cover"
                        />
                      ) : (
                        <Box
                          className="album-tile__fallback"
                          aria-hidden
                          sx={{
                            width: '100%',
                            height: '100%',
                            display: 'grid',
                            placeItems: 'center',
                            background: `linear-gradient(145deg, var(--td-cover-start), var(--td-cover-end))`,
                            color: 'rgba(232, 241, 240, 0.7)',
                          }}
                        >
                          <AlbumIcon sx={{ fontSize: 40 }} />
                        </Box>
                      )}
                    </Box>
                    <Box className="album-tile__meta" sx={{ mt: 1 }}>
                      <Box
                        className="album-tile__title"
                        sx={{
                          typography: 'body2',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {localizeAlbumName(tile.name, t)}
                      </Box>
                      <Box
                        className="album-tile__subtitle"
                        sx={{ typography: 'caption', color: 'text.secondary' }}
                      >
                        {t('album.trackCount', { count: tile.trackCount })}
                      </Box>
                    </Box>
                  </Box>
                ))}
              </Box>
            )
          })}
        </Box>
      </Box>
    </Box>
  )
}

// src/components/AlbumGallery.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import CoverImg from '@/components/CoverImg.vue'
import { useVirtualListHost } from '@/composables/useVirtualListHost'
import {
  ALBUM_GALLERY_GAP_PX,
  albumGalleryColumns,
  albumGalleryRowHeight,
  chunkIntoRows,
} from '@/lib/albumGalleryLayout'
import { localizeAlbumName } from '@/lib/catalog/displayLabels'
import { capVirtualListHeight, virtualListNeedsScroll } from '@/lib/virtualListHeight'

export type AlbumGalleryTile = {
  name: string
  trackCount: number
  coverSrc?: string
}

const props = defineProps<{
  tiles: AlbumGalleryTile[]
  /** Build the router `to` for a tile name. */
  pathFor: (name: string) => string
}>()

const { t } = useI18n()
const { listHost, hostHeight, hostWidth } = useVirtualListHost({ observeWidth: true })

const columns = computed(() => albumGalleryColumns(hostWidth.value))

const albumRows = computed(() =>
  chunkIntoRows(props.tiles, columns.value).map((tiles, index) => ({
    key: `row-${index}-${tiles[0]?.name ?? index}`,
    tiles,
  })),
)

const rowHeight = computed(() => albumGalleryRowHeight(hostWidth.value, columns.value))

const listHeight = computed(() =>
  capVirtualListHeight(albumRows.value.length, rowHeight.value, hostHeight.value),
)

const listFlush = computed(
  () => !virtualListNeedsScroll(albumRows.value.length, rowHeight.value, hostHeight.value),
)

const rowStyle = computed(() => ({
  gap: `${ALBUM_GALLERY_GAP_PX}px`,
  gridTemplateColumns: `repeat(${columns.value}, minmax(0, 1fr))`,
}))
</script>

<template>
  <div ref="listHost" class="list-host album-gallery">
    <v-virtual-scroll
      :items="albumRows"
      item-key="key"
      :item-height="rowHeight"
      class="album-list"
      :class="{ 'album-list--flush': listFlush }"
      :height="listHeight"
    >
      <template #default="{ item: row }">
        <div class="album-gallery-row" :style="rowStyle">
          <RouterLink
            v-for="tile in row.tiles"
            :key="tile.name"
            class="album-tile"
            :to="pathFor(tile.name)"
          >
            <div class="album-tile__art">
              <CoverImg
                v-if="tile.coverSrc"
                :src="tile.coverSrc"
                :aspect-ratio="1"
                class="album-tile__cover"
              />
              <div v-else class="album-tile__fallback" aria-hidden="true">
                <v-icon icon="mdi-album" size="40" />
              </div>
            </div>
            <div class="album-tile__meta">
              <div class="album-tile__title text-body-2">
                {{ localizeAlbumName(tile.name, t) }}
              </div>
              <div class="album-tile__subtitle text-caption text-medium-emphasis">
                {{ t('album.trackCount', { count: tile.trackCount }) }}
              </div>
            </div>
          </RouterLink>
        </div>
      </template>
    </v-virtual-scroll>
  </div>
</template>

<style scoped>
.list-host {
  flex: 1 1 auto;
  min-height: 0;
}

.album-list {
  background: transparent;
}

.album-list--flush {
  overflow-y: hidden !important;
}

.album-gallery-row {
  display: grid;
  box-sizing: border-box;
  /* Bottom padding matches the row-height gap so tiles align with item-height. */
  padding-bottom: v-bind('`${ALBUM_GALLERY_GAP_PX}px`');
}

.album-tile {
  color: inherit;
  text-decoration: none;
  animation: rise 0.45s ease both;
  min-width: 0;
}

.album-tile:hover .album-tile__art {
  transform: translateY(calc(var(--v-motion-cover) * -1));
}

.album-tile__art {
  aspect-ratio: 1;
  border-radius: var(--v-radius-lg);
  overflow: hidden;
  box-shadow: var(--v-cover-shadow);
  transition: transform 0.2s ease;
}

.album-tile__cover {
  width: 100%;
  height: 100%;
}

.album-tile__fallback {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  background: linear-gradient(
    145deg,
    rgb(var(--v-theme-cover-start)),
    rgb(var(--v-theme-cover-end))
  );
  color: rgba(var(--v-theme-on-surface), 0.7);
}

.album-tile__meta {
  margin-top: 0.5rem;
}

.album-tile__title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

@keyframes rise {
  from {
    opacity: 0;
    transform: translateY(var(--v-motion-rise));
  }
  to {
    opacity: 1;
    transform: none;
  }
}
</style>
