// src/components/AppHeader.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'

import brandIconUrl from '@/assets/brand-icon.png'
import { writeStoredLocale } from '@/lib/locale'
import { shouldCollapseNav } from '@/lib/navLayout'

const { t, locale } = useI18n()
const route = useRoute()
const drawerOpen = ref(false)
const compactNav = ref(true)
const openMenus = ref<Record<string, boolean>>({})

const appBarRef = ref<{ $el?: HTMLElement } | null>(null)
const desktopNavRef = ref<HTMLElement | null>(null)
let resizeObserver: ResizeObserver | null = null

type NavRouteLink = { to: string; key: string; icon: string }
type NavActionLink = { action: 'feedback'; key: string; icon: string }
type NavLocaleLink = { locale: 'en' | 'zh'; key: string; icon: string }
type NavLink = NavRouteLink | NavActionLink | NavLocaleLink
type NavGroup = { key: string; icon: string; children: readonly NavLink[]; menuTestId: string }
type NavItem = NavRouteLink | NavGroup

function isNavGroup(item: NavItem): item is NavGroup {
  return 'children' in item
}

function isActionNavLink(item: NavLink): item is NavActionLink {
  return 'action' in item
}

function isLocaleNavLink(item: NavLink): item is NavLocaleLink {
  return 'locale' in item
}

function updateCompactNav() {
  const toolbarContent = appBarRef.value?.$el?.querySelector(
    '.v-toolbar__content',
  ) as HTMLElement | null
  const brand = toolbarContent?.querySelector('.brand') as HTMLElement | null
  const nav = desktopNavRef.value
  if (!toolbarContent || !brand || !nav) return

  const availableWidth = toolbarContent.clientWidth - brand.offsetWidth
  compactNav.value = shouldCollapseNav(nav.scrollWidth, availableWidth)
}

function observeLayout() {
  resizeObserver?.disconnect()
  resizeObserver = null

  const toolbarContent = appBarRef.value?.$el?.querySelector(
    '.v-toolbar__content',
  ) as HTMLElement | null
  if (!toolbarContent || typeof ResizeObserver === 'undefined') {
    updateCompactNav()
    return
  }

  resizeObserver = new ResizeObserver(() => {
    updateCompactNav()
  })
  resizeObserver.observe(toolbarContent)
  if (desktopNavRef.value) resizeObserver.observe(desktopNavRef.value)
  updateCompactNav()
}

watch(locale, async () => {
  writeStoredLocale(locale.value)
  await nextTick()
  updateCompactNav()
})

watch(
  () => route.fullPath,
  () => {
    drawerOpen.value = false
    openMenus.value = {}
  },
)

onMounted(() => {
  observeLayout()
})

onBeforeUnmount(() => {
  resizeObserver?.disconnect()
  resizeObserver = null
})

const GITHUB_ISSUES_URL = 'https://github.com/mengtaoxin/tdmusic/issues'
const confirmFeedbackOpen = ref(false)

const moreChildren: readonly NavLink[] = [
  { to: '/search', key: 'nav.search', icon: 'mdi-magnify' },
  { to: '/settings', key: 'nav.settings', icon: 'mdi-cog' },
  { to: '/config-guides', key: 'nav.configGuides', icon: 'mdi-file-document-outline' },
  { to: '/about', key: 'nav.about', icon: 'mdi-information-outline' },
  { to: '/logs', key: 'nav.logs', icon: 'mdi-text-box-outline' },
  { action: 'feedback', key: 'nav.feedback', icon: 'mdi-message-text-outline' },
]

const localeChildren: readonly NavLocaleLink[] = [
  { locale: 'en', key: 'locale.en', icon: 'mdi-translate' },
  { locale: 'zh', key: 'locale.zh', icon: 'mdi-translate' },
]

const navItems: readonly NavItem[] = [
  { to: '/now-playing', key: 'nav.nowPlaying', icon: 'mdi-play-circle' },
  { to: '/music', key: 'nav.musicList', icon: 'mdi-music-box-multiple' },
  { to: '/playlists', key: 'nav.playlist', icon: 'mdi-playlist-music' },
  { to: '/artists', key: 'nav.artistList', icon: 'mdi-account-music' },
  { to: '/albums', key: 'nav.albumList', icon: 'mdi-album' },
  { key: 'nav.more', icon: 'mdi-dots-horizontal', children: moreChildren, menuTestId: 'nav-more' },
  {
    key: 'nav.language',
    icon: 'mdi-translate',
    children: localeChildren,
    menuTestId: 'nav-locale',
  },
]

const moreChildPaths: readonly string[] = moreChildren.flatMap((item) =>
  isActionNavLink(item) || isLocaleNavLink(item) ? [] : [item.to],
)

const moreGroupActive = computed(() => moreChildPaths.includes(route.path))

function groupActive(item: NavGroup): boolean {
  if (item.key === 'nav.more') return moreGroupActive.value
  if (item.key === 'nav.language') return false
  return false
}

function setLocale(value: 'en' | 'zh') {
  locale.value = value
}

function openFeedbackConfirm() {
  confirmFeedbackOpen.value = true
}

function confirmOpenFeedback() {
  confirmFeedbackOpen.value = false
  window.open(GITHUB_ISSUES_URL, '_blank', 'noopener,noreferrer')
}

function childBindings(child: NavLink) {
  if (isLocaleNavLink(child)) {
    return {
      'data-testid': `locale-option-${child.locale}`,
      active: locale.value === child.locale,
      onClick: () => {
        setLocale(child.locale)
        drawerOpen.value = false
      },
    }
  }
  if (isActionNavLink(child)) {
    return {
      'data-testid': 'nav-feedback',
      onClick: () => {
        drawerOpen.value = false
        openFeedbackConfirm()
      },
    }
  }
  return {
    to: child.to,
    onClick: () => {
      drawerOpen.value = false
    },
  }
}

function desktopChildBindings(child: NavLink) {
  if (isLocaleNavLink(child)) {
    return {
      'data-testid': `locale-option-${child.locale}`,
      active: locale.value === child.locale,
      onClick: () => setLocale(child.locale),
    }
  }
  if (isActionNavLink(child)) {
    return {
      'data-testid': 'nav-feedback',
      onClick: openFeedbackConfirm,
    }
  }
  return { to: child.to }
}

function childTitle(child: NavLink): string {
  return t(child.key)
}
</script>

<template>
  <v-navigation-drawer
    v-model="drawerOpen"
    data-testid="nav-drawer"
    temporary
    location="start"
    width="280"
    class="nav-drawer"
  >
    <v-list density="compact" nav>
      <template v-for="item in navItems" :key="item.key">
        <v-list-group v-if="isNavGroup(item)" :value="item.key">
          <template #activator="{ props: activatorProps }">
            <v-list-item
              v-bind="activatorProps"
              :title="t(item.key)"
              :prepend-icon="item.icon"
              :active="groupActive(item)"
            />
          </template>
          <v-list-item
            v-for="child in item.children"
            :key="child.key"
            v-bind="childBindings(child)"
            :title="childTitle(child)"
            :prepend-icon="child.icon"
          />
        </v-list-group>
        <v-list-item
          v-else
          :to="item.to"
          :title="t(item.key)"
          :prepend-icon="item.icon"
          @click="drawerOpen = false"
        />
      </template>
    </v-list>
  </v-navigation-drawer>

  <v-dialog v-model="confirmFeedbackOpen" max-width="420">
    <v-card>
      <v-card-title>{{ t('nav.feedback') }}</v-card-title>
      <v-card-text>{{ t('nav.feedbackConfirm') }}</v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn variant="text" @click="confirmFeedbackOpen = false">{{
          t('settings.cancel')
        }}</v-btn>
        <v-btn color="primary" variant="tonal" @click="confirmOpenFeedback">
          {{ t('settings.confirm') }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>

  <v-app-bar ref="appBarRef" flat class="app-bar" color="transparent">
    <v-app-bar-title class="brand text-secondary flex-grow-0 flex-shrink-0">
      <RouterLink to="/" data-testid="brand-title" class="brand-mark header-centerline">
        <img
          data-testid="brand-icon"
          class="brand-icon"
          :src="brandIconUrl"
          width="28"
          height="28"
          alt=""
        />
        tdmusic
        <span data-testid="brand-beta" class="brand-beta">{{ t('nav.beta') }}</span>
      </RouterLink>
    </v-app-bar-title>

    <v-btn
      v-if="compactNav"
      data-testid="nav-menu-toggle"
      class="header-centerline"
      icon
      variant="text"
      :aria-label="t('nav.openMenu')"
      @click="drawerOpen = !drawerOpen"
    >
      <v-icon>mdi-menu</v-icon>
    </v-btn>

    <template #append>
      <nav
        ref="desktopNavRef"
        data-testid="desktop-nav"
        class="desktop-nav header-centerline align-center ga-1"
        :class="{ 'desktop-nav--measure': compactNav }"
        :aria-hidden="compactNav ? 'true' : undefined"
      >
        <template v-for="item in navItems" :key="item.key">
          <v-menu
            v-if="isNavGroup(item)"
            v-model="openMenus[item.key]"
            location="bottom end"
            :close-on-content-click="true"
            transition="fade-transition"
          >
            <template #activator="{ props: activatorProps }">
              <v-btn
                v-bind="activatorProps"
                :data-testid="`${item.menuTestId}-toggle`"
                :prepend-icon="item.icon"
                variant="text"
                size="small"
                :active="groupActive(item)"
                :tabindex="compactNav ? -1 : undefined"
              >
                {{ t(item.key) }}
              </v-btn>
            </template>
            <v-list density="compact" :data-testid="`${item.menuTestId}-menu`" min-width="160">
              <v-list-item
                v-for="child in item.children"
                :key="child.key"
                v-bind="desktopChildBindings(child)"
                :title="childTitle(child)"
                :prepend-icon="child.icon"
              />
            </v-list>
          </v-menu>
          <v-btn
            v-else
            :to="item.to"
            :prepend-icon="item.icon"
            variant="text"
            size="small"
            :tabindex="compactNav ? -1 : undefined"
          >
            {{ t(item.key) }}
          </v-btn>
        </template>
      </nav>
    </template>
  </v-app-bar>
</template>

<style scoped>
.app-bar {
  border-bottom: 1px solid rgba(var(--v-theme-secondary), var(--v-border-opacity));
  backdrop-filter: blur(var(--v-blur-header));
}

.app-bar :deep(.v-toolbar__content) {
  align-items: center;
}

.brand {
  font-weight: 700;
  letter-spacing: 0.04em;
  flex-basis: auto;
  min-width: max-content;
  align-self: center;
  margin-block: 0;
  padding-block: 0;
  line-height: 1.25;
}

.brand :deep(.v-toolbar-title__placeholder) {
  display: flex;
  align-items: center;
  overflow: visible;
  width: auto;
  height: 100%;
}

.header-centerline {
  align-self: center;
}

.header-centerline.v-btn--icon {
  height: 2.25rem;
  width: 2.25rem;
}

.brand-mark {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  white-space: nowrap;
  line-height: 1.25;
  height: 2.25rem;
  color: inherit;
  text-decoration: none;
}

.brand-icon {
  display: block;
  border-radius: var(--v-radius-md);
  flex-shrink: 0;
}

.brand-beta {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  margin-inline-start: 0.15rem;
  padding: 0.05rem 0.35rem;
  border-radius: 0.25rem;
  font-size: 0.5rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  line-height: 1.2;
  text-transform: uppercase;
  color: rgb(var(--v-theme-on-secondary));
  background: rgba(var(--v-theme-secondary), 0.85);
  flex-shrink: 0;
}

.desktop-nav {
  display: flex;
  flex-wrap: nowrap;
  align-items: center;
  white-space: nowrap;
  height: 2.25rem;
}

.desktop-nav :deep(.v-btn) {
  height: 2.25rem;
  min-height: 2.25rem;
  /* Beat Vuetify reset `button { font-size: inherit }` so menu <button>s match link items. */
  font-size: var(--v-btn-size);
}

.desktop-nav--measure {
  position: absolute;
  visibility: hidden;
  pointer-events: none;
}

.nav-drawer {
  border-inline-end: 1px solid rgba(var(--v-theme-secondary), var(--v-border-opacity));
}
</style>

// src/components/AppHeader.tsx
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import AppBar from '@mui/material/AppBar'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Collapse from '@mui/material/Collapse'
import Dialog from '@mui/material/Dialog'
import DialogActions from '@mui/material/DialogActions'
import DialogContent from '@mui/material/DialogContent'
import DialogTitle from '@mui/material/DialogTitle'
import Drawer from '@mui/material/Drawer'
import IconButton from '@mui/material/IconButton'
import List from '@mui/material/List'
import ListItemButton from '@mui/material/ListItemButton'
import ListItemIcon from '@mui/material/ListItemIcon'
import ListItemText from '@mui/material/ListItemText'
import Menu from '@mui/material/Menu'
import MenuItem from '@mui/material/MenuItem'
import Toolbar from '@mui/material/Toolbar'
import AlbumIcon from '@mui/icons-material/Album'
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined'
import FeedbackOutlinedIcon from '@mui/icons-material/FeedbackOutlined'
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined'
import LibraryMusicIcon from '@mui/icons-material/LibraryMusic'
import MenuIcon from '@mui/icons-material/Menu'
import MoreHorizIcon from '@mui/icons-material/MoreHoriz'
import NotesOutlinedIcon from '@mui/icons-material/NotesOutlined'
import PersonIcon from '@mui/icons-material/Person'
import PlayCircleIcon from '@mui/icons-material/PlayCircle'
import QueueMusicIcon from '@mui/icons-material/QueueMusic'
import SearchIcon from '@mui/icons-material/Search'
import SettingsIcon from '@mui/icons-material/Settings'
import TranslateIcon from '@mui/icons-material/Translate'
import ExpandLess from '@mui/icons-material/ExpandLess'
import ExpandMore from '@mui/icons-material/ExpandMore'
import { Link, useRouterState } from '@tanstack/react-router'
import { useTranslation } from 'react-i18next'
import type { SvgIconComponent } from '@mui/icons-material'

import brandIconUrl from '@/assets/brand-icon.png'
import i18n from '@/i18n'
import { writeStoredLocale, type AppLocale } from '@/lib/locale'
import { shouldCollapseNav } from '@/lib/navLayout'

const GITHUB_ISSUES_URL = 'https://github.com/mengtaoxin/tdmusic/issues'

type NavRouteLink = { to: string; key: string; Icon: SvgIconComponent }
type NavActionLink = { action: 'feedback'; key: string; Icon: SvgIconComponent }
type NavLocaleLink = { locale: AppLocale; key: string; Icon: SvgIconComponent }
type NavLink = NavRouteLink | NavActionLink | NavLocaleLink
type NavGroup = {
  key: string
  Icon: SvgIconComponent
  children: readonly NavLink[]
  menuTestId: string
}
type NavItem = NavRouteLink | NavGroup

function isNavGroup(item: NavItem): item is NavGroup {
  return 'children' in item
}

function isActionNavLink(item: NavLink): item is NavActionLink {
  return 'action' in item
}

function isLocaleNavLink(item: NavLink): item is NavLocaleLink {
  return 'locale' in item
}

const moreChildren: readonly NavLink[] = [
  { to: '/search', key: 'nav.search', Icon: SearchIcon },
  { to: '/settings', key: 'nav.settings', Icon: SettingsIcon },
  { to: '/config-guides', key: 'nav.configGuides', Icon: DescriptionOutlinedIcon },
  { to: '/about', key: 'nav.about', Icon: InfoOutlinedIcon },
  { to: '/logs', key: 'nav.logs', Icon: NotesOutlinedIcon },
  { action: 'feedback', key: 'nav.feedback', Icon: FeedbackOutlinedIcon },
]

const localeChildren: readonly NavLocaleLink[] = [
  { locale: 'en', key: 'locale.en', Icon: TranslateIcon },
  { locale: 'zh', key: 'locale.zh', Icon: TranslateIcon },
]

const navItems: readonly NavItem[] = [
  { to: '/now-playing', key: 'nav.nowPlaying', Icon: PlayCircleIcon },
  { to: '/music', key: 'nav.musicList', Icon: LibraryMusicIcon },
  { to: '/playlists', key: 'nav.playlist', Icon: QueueMusicIcon },
  { to: '/artists', key: 'nav.artistList', Icon: PersonIcon },
  { to: '/albums', key: 'nav.albumList', Icon: AlbumIcon },
  {
    key: 'nav.language',
    Icon: TranslateIcon,
    children: localeChildren,
    menuTestId: 'nav-locale',
  },
  { key: 'nav.more', Icon: MoreHorizIcon, children: moreChildren, menuTestId: 'nav-more' },
]

const moreChildPaths: readonly string[] = moreChildren.flatMap((item) =>
  isActionNavLink(item) || isLocaleNavLink(item) ? [] : [item.to],
)

type DesktopMenuState = { id: string; anchor: HTMLElement } | null

export function AppHeader() {
  const { t, i18n: i18nInstance } = useTranslation()
  const pathname = useRouterState({ select: (s) => s.location.pathname })
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [compactNav, setCompactNav] = useState(true)
  const [confirmFeedbackOpen, setConfirmFeedbackOpen] = useState(false)
  const [desktopMenu, setDesktopMenu] = useState<DesktopMenuState>(null)
  const [drawerExpanded, setDrawerExpanded] = useState<Record<string, boolean>>({})

  const toolbarRef = useRef<HTMLDivElement | null>(null)
  const brandRef = useRef<HTMLDivElement | null>(null)
  const desktopNavRef = useRef<HTMLElement | null>(null)

  const locale = (i18nInstance.language?.startsWith('zh') ? 'zh' : 'en') as AppLocale
  const moreGroupActive = moreChildPaths.includes(pathname)

  const updateCompactNav = useCallback(() => {
    const toolbar = toolbarRef.current
    const brand = brandRef.current
    const nav = desktopNavRef.current
    if (!toolbar || !brand || !nav) return
    const availableWidth = toolbar.clientWidth - brand.offsetWidth
    setCompactNav(shouldCollapseNav(nav.scrollWidth, availableWidth))
  }, [])

  useEffect(() => {
    const toolbar = toolbarRef.current
    if (!toolbar || typeof ResizeObserver === 'undefined') {
      updateCompactNav()
      return
    }
    const observer = new ResizeObserver(() => {
      updateCompactNav()
    })
    observer.observe(toolbar)
    if (desktopNavRef.current) observer.observe(desktopNavRef.current)
    updateCompactNav()
    return () => observer.disconnect()
  }, [updateCompactNav, locale])

  useEffect(() => {
    setDrawerOpen(false)
    setDesktopMenu(null)
  }, [pathname])

  useEffect(() => {
    // Remeasure after locale labels change width.
    const id = requestAnimationFrame(() => updateCompactNav())
    return () => cancelAnimationFrame(id)
  }, [locale, t, updateCompactNav])

  function setLocale(value: AppLocale) {
    writeStoredLocale(value)
    void i18n.changeLanguage(value)
  }

  function openFeedbackConfirm() {
    setConfirmFeedbackOpen(true)
  }

  function confirmOpenFeedback() {
    setConfirmFeedbackOpen(false)
    window.open(GITHUB_ISSUES_URL, '_blank', 'noopener,noreferrer')
  }

  function groupActive(item: NavGroup): boolean {
    if (item.key === 'nav.more') return moreGroupActive
    return false
  }

  function toggleDrawerGroup(key: string) {
    setDrawerExpanded((prev) => ({ ...prev, [key]: !prev[key] }))
  }

  function renderDesktopChild(child: NavLink): ReactNode {
    if (isLocaleNavLink(child)) {
      return (
        <MenuItem
          key={child.key}
          data-testid={`locale-option-${child.locale}`}
          selected={locale === child.locale}
          onClick={() => {
            setLocale(child.locale)
            setDesktopMenu(null)
          }}
        >
          <ListItemIcon>
            <child.Icon fontSize="small" />
          </ListItemIcon>
          {t(child.key)}
        </MenuItem>
      )
    }
    if (isActionNavLink(child)) {
      return (
        <MenuItem
          key={child.key}
          data-testid="nav-feedback"
          onClick={() => {
            setDesktopMenu(null)
            openFeedbackConfirm()
          }}
        >
          <ListItemIcon>
            <child.Icon fontSize="small" />
          </ListItemIcon>
          {t(child.key)}
        </MenuItem>
      )
    }
    return (
      <MenuItem key={child.key} component={Link} to={child.to} onClick={() => setDesktopMenu(null)}>
        <ListItemIcon>
          <child.Icon fontSize="small" />
        </ListItemIcon>
        {t(child.key)}
      </MenuItem>
    )
  }

  function renderDrawerChild(child: NavLink): ReactNode {
    if (isLocaleNavLink(child)) {
      return (
        <ListItemButton
          key={child.key}
          data-testid={`locale-option-${child.locale}`}
          selected={locale === child.locale}
          sx={{ pl: 4 }}
          onClick={() => {
            setLocale(child.locale)
            setDrawerOpen(false)
          }}
        >
          <ListItemIcon>
            <child.Icon fontSize="small" />
          </ListItemIcon>
          <ListItemText primary={t(child.key)} />
        </ListItemButton>
      )
    }
    if (isActionNavLink(child)) {
      return (
        <ListItemButton
          key={child.key}
          data-testid="nav-feedback"
          sx={{ pl: 4 }}
          onClick={() => {
            setDrawerOpen(false)
            openFeedbackConfirm()
          }}
        >
          <ListItemIcon>
            <child.Icon fontSize="small" />
          </ListItemIcon>
          <ListItemText primary={t(child.key)} />
        </ListItemButton>
      )
    }
    return (
      <ListItemButton
        key={child.key}
        component={Link}
        to={child.to}
        sx={{ pl: 4 }}
        selected={pathname === child.to}
        onClick={() => setDrawerOpen(false)}
      >
        <ListItemIcon>
          <child.Icon fontSize="small" />
        </ListItemIcon>
        <ListItemText primary={t(child.key)} />
      </ListItemButton>
    )
  }

  return (
    <>
      <Drawer
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
        anchor="left"
        keepMounted
        className="nav-drawer"
        slotProps={{
          paper: {
            sx: {
              width: 280,
              borderInlineEnd: (th) =>
                `1px solid color-mix(in srgb, ${th.palette.secondary.main} 20%, transparent)`,
            },
          },
        }}
      >
        <Box data-testid="nav-drawer" sx={{ height: '100%' }}>
          <List dense component="nav" sx={{ pt: 1 }}>
            {navItems.map((item) => {
              if (isNavGroup(item)) {
                const open = Boolean(drawerExpanded[item.key])
                return (
                  <Box key={item.key} className="v-list-group">
                    <ListItemButton
                      className="v-list-group__header"
                      selected={groupActive(item)}
                      onClick={() => toggleDrawerGroup(item.key)}
                    >
                      <ListItemIcon>
                        <item.Icon fontSize="small" />
                      </ListItemIcon>
                      <ListItemText primary={t(item.key)} />
                      {open ? <ExpandLess /> : <ExpandMore />}
                    </ListItemButton>
                    <Collapse in={open} timeout="auto" unmountOnExit>
                      <List dense disablePadding>
                        {item.children.map((child) => renderDrawerChild(child))}
                      </List>
                    </Collapse>
                  </Box>
                )
              }
              return (
                <ListItemButton
                  key={item.key}
                  component={Link}
                  to={item.to}
                  selected={pathname === item.to}
                  onClick={() => setDrawerOpen(false)}
                >
                  <ListItemIcon>
                    <item.Icon fontSize="small" />
                  </ListItemIcon>
                  <ListItemText primary={t(item.key)} />
                </ListItemButton>
              )
            })}
          </List>
        </Box>
      </Drawer>

      <Dialog
        open={confirmFeedbackOpen}
        onClose={() => setConfirmFeedbackOpen(false)}
        maxWidth="xs"
        fullWidth
      >
        <DialogTitle>{t('nav.feedback')}</DialogTitle>
        <DialogContent>{t('nav.feedbackConfirm')}</DialogContent>
        <DialogActions>
          <Button onClick={() => setConfirmFeedbackOpen(false)}>{t('settings.cancel')}</Button>
          <Button color="primary" variant="contained" onClick={confirmOpenFeedback}>
            {t('settings.confirm')}
          </Button>
        </DialogActions>
      </Dialog>

      <AppBar
        position="static"
        elevation={0}
        color="transparent"
        className="app-bar"
        sx={{
          borderBottom: (th) =>
            `1px solid color-mix(in srgb, ${th.palette.secondary.main} 20%, transparent)`,
          backdropFilter: `blur(var(--td-blur-header))`,
        }}
      >
        <Toolbar
          ref={toolbarRef}
          className="toolbar-content"
          sx={{ alignItems: 'center', gap: 0.5, minHeight: 64 }}
        >
          <Box
            ref={brandRef}
            className="brand flex-grow-0 flex-shrink-0"
            sx={{
              fontWeight: 700,
              letterSpacing: '0.04em',
              flexGrow: 0,
              flexShrink: 0,
              color: 'secondary.main',
              alignSelf: 'center',
              minWidth: 'max-content',
            }}
          >
            <Box
              component={Link}
              to="/"
              data-testid="brand-title"
              className="brand-mark header-centerline"
              sx={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 1,
                whiteSpace: 'nowrap',
                lineHeight: 1.25,
                height: '2.25rem',
                color: 'inherit',
                textDecoration: 'none',
              }}
            >
              <Box
                component="img"
                data-testid="brand-icon"
                className="brand-icon"
                src={brandIconUrl}
                width={28}
                height={28}
                alt=""
                sx={{ display: 'block', borderRadius: 'var(--td-radius-md)', flexShrink: 0 }}
              />
              tdmusic
              <Box
                component="span"
                data-testid="brand-beta"
                className="brand-beta"
                sx={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  ml: 0.25,
                  px: 0.7,
                  py: 0.1,
                  borderRadius: 0.5,
                  fontSize: '0.5rem',
                  fontWeight: 700,
                  letterSpacing: '0.06em',
                  lineHeight: 1.2,
                  textTransform: 'uppercase',
                  color: 'secondary.contrastText',
                  bgcolor: 'rgba(255, 193, 7, 0.85)',
                  flexShrink: 0,
                }}
              >
                {t('nav.beta')}
              </Box>
            </Box>
          </Box>

          {compactNav ? (
            <IconButton
              data-testid="nav-menu-toggle"
              className="header-centerline"
              aria-label={t('nav.openMenu')}
              onClick={() => setDrawerOpen((open) => !open)}
              sx={{ alignSelf: 'center', width: '2.25rem', height: '2.25rem' }}
            >
              <MenuIcon />
            </IconButton>
          ) : null}

          <Box sx={{ flex: 1 }} />

          <Box
            component="nav"
            ref={desktopNavRef}
            data-testid="desktop-nav"
            className={`desktop-nav header-centerline${compactNav ? ' desktop-nav--measure' : ''}`}
            aria-hidden={compactNav ? true : undefined}
            sx={{
              display: 'flex',
              flexWrap: 'nowrap',
              alignItems: 'center',
              whiteSpace: 'nowrap',
              height: '2.25rem',
              gap: 0.5,
              ...(compactNav
                ? {
                    position: 'absolute',
                    visibility: 'hidden',
                    pointerEvents: 'none',
                  }
                : {}),
            }}
          >
            {navItems.map((item) => {
              if (isNavGroup(item)) {
                const menuId = `${item.menuTestId}-${pathname}`
                const open = desktopMenu?.id === menuId
                return (
                  <Box key={menuId}>
                    <Button
                      data-testid={`${item.menuTestId}-toggle`}
                      size="small"
                      variant="text"
                      color="inherit"
                      startIcon={<item.Icon fontSize="small" />}
                      tabIndex={compactNav ? -1 : undefined}
                      aria-haspopup="true"
                      aria-expanded={open ? 'true' : undefined}
                      onClick={(event) =>
                        setDesktopMenu(open ? null : { id: menuId, anchor: event.currentTarget })
                      }
                      sx={{
                        height: '2.25rem',
                        minHeight: '2.25rem',
                        textTransform: 'none',
                        ...(groupActive(item) ? { color: 'primary.main' } : {}),
                      }}
                    >
                      {t(item.key)}
                    </Button>
                    <Menu
                      key={menuId}
                      anchorEl={open ? desktopMenu.anchor : null}
                      open={open}
                      onClose={() => setDesktopMenu(null)}
                      anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
                      transformOrigin={{ vertical: 'top', horizontal: 'right' }}
                      transitionDuration={150}
                      slotProps={{
                        paper: {
                          'data-testid': `${item.menuTestId}-menu`,
                        } as { 'data-testid': string },
                        list: {
                          dense: true,
                          sx: { minWidth: 160 },
                        },
                      }}
                    >
                      {item.children.map((child) => renderDesktopChild(child))}
                    </Menu>
                  </Box>
                )
              }
              return (
                <Button
                  key={item.key}
                  component={Link}
                  to={item.to}
                  size="small"
                  variant="text"
                  color="inherit"
                  startIcon={<item.Icon fontSize="small" />}
                  tabIndex={compactNav ? -1 : undefined}
                  sx={{
                    height: '2.25rem',
                    minHeight: '2.25rem',
                    textTransform: 'none',
                    ...(pathname === item.to ? { color: 'primary.main' } : {}),
                  }}
                >
                  {t(item.key)}
                </Button>
              )
            })}
          </Box>
        </Toolbar>
      </AppBar>
    </>
  )
}
