// src/components/AudioHost.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'

import { appendAppLog } from '@/lib/appLogStore'
import { syncMediaSession } from '@/lib/mediaSession'
import { createPlaybackSession } from '@/lib/playbackSession'
import { prefetchUpcoming } from '@/lib/prefetchUpcoming'
import { resolvePlayableUrl } from '@/lib/resolvePlayableUrl'
import { useCatalogStore } from '@/stores/catalog'
import { usePlayerStore } from '@/stores/player'

const audioRef = ref<HTMLAudioElement | null>(null)
const catalog = useCatalogStore()
const player = usePlayerStore()

let lastTimePersist = 0
let lastMediaSessionSync = 0
const PREFETCH_COUNT = 3
const MEDIA_SESSION_SYNC_MS = 1000

function resolveTrackForPrefetch(id: string) {
  const track = catalog.trackById.get(id)
  if (!track) return undefined
  return { id: track.id, path: track.path }
}

function schedulePrefetch() {
  void prefetchUpcoming(player.queue, player.currentIndex, {
    count: PREFETCH_COUNT,
    repeatMode: player.repeatMode,
    shuffle: player.shuffle,
    resolveTrack: resolveTrackForPrefetch,
    onTrackCached: (id) => catalog.scheduleEnrichTrack(id),
  })
}

const session = createPlaybackSession(
  () => audioRef.value,
  {
    getCurrentId: () => player.currentId,
    getQueueLength: () => player.queue.length,
    getSeekTo: () => player.seekTo,
    getPendingPlay: () => player.pendingPlay,
    clearSeekTo: () => {
      player.seekTo = null
    },
    pause: () => player.pause(),
    skip: () => player.skip(),
    getTrack: (id) => {
      const track = catalog.trackById.get(id)
      if (!track) return undefined
      return { id: track.id, path: track.path }
    },
  },
  {
    resolvePlayableUrl,
    appendAppLog: (message) => {
      void appendAppLog(message)
    },
    scheduleEnrichTrack: (id) => catalog.scheduleEnrichTrack(id),
    schedulePrefetch,
  },
)

function updateMediaSession() {
  const track = player.currentId ? catalog.trackById.get(player.currentId) : undefined
  syncMediaSession(track, player)
}

watch(
  () => player.loadToken,
  () => {
    void session.loadCurrent()
  },
)

watch(
  () =>
    [
      player.currentId,
      player.playing,
      player.currentId ? catalog.trackById.get(player.currentId)?.displayTitle : null,
      player.currentId ? catalog.trackById.get(player.currentId)?.displayCover : null,
    ] as const,
  () => {
    updateMediaSession()
  },
)

watch(
  () => player.queue,
  () => {
    if (player.currentId) schedulePrefetch()
  },
  { deep: true },
)

watch(
  () => player.repeatMode,
  (mode) => {
    const audio = audioRef.value
    if (audio) audio.loop = mode === 'one'
  },
)

watch(
  () => player.pendingPlay,
  (want) => {
    const audio = audioRef.value
    if (!audio) return
    if (want) {
      void audio.play().catch(() => player.pause())
    } else {
      audio.pause()
    }
  },
)

watch(
  () => player.seekTo,
  (value) => {
    const audio = audioRef.value
    if (audio && value != null && Number.isFinite(value) && audio.src) {
      audio.currentTime = value
      player.seekTo = null
    }
  },
)

function onTimeUpdate() {
  const audio = audioRef.value
  if (!audio) return
  player.currentTime = audio.currentTime
  player.duration = audio.duration || 0
  const now = Date.now()
  if (now - lastMediaSessionSync >= MEDIA_SESSION_SYNC_MS) {
    lastMediaSessionSync = now
    updateMediaSession()
  }
  if (now - lastTimePersist > 2000) {
    lastTimePersist = now
    player.flushPersist()
  }
}

function onPlay() {
  player.playing = true
}

function onPause() {
  const audio = audioRef.value
  // Natural end fires pause before ended; let onEnded own that transition.
  if (audio?.ended) return
  // External interrupt (other app / OS) pauses the element without store.pause();
  // clear pendingPlay so a later play() re-triggers the pendingPlay watcher.
  player.pendingPlay = false
  player.playing = false
  player.flushPersist()
}

function onEnded() {
  player.onEnded()
  // Repeat-one also sets audio.loop; this path covers seek+play if ended still fires
  // (e.g. loop was off) when pendingPlay was already true so its watch does not re-run.
  if (player.repeatMode === 'one') {
    const audio = audioRef.value
    if (!audio) return
    const seek = player.seekTo
    audio.currentTime = seek != null && Number.isFinite(seek) ? seek : 0
    player.seekTo = null
    void audio.play().catch(() => player.pause())
  }
}

function onVisibilityFlush() {
  player.flushPersist()
}

onMounted(() => {
  const audio = audioRef.value
  if (audio) audio.loop = player.repeatMode === 'one'
  document.addEventListener('visibilitychange', onVisibilityFlush)
  window.addEventListener('pagehide', onVisibilityFlush)
  updateMediaSession()
})

onUnmounted(() => {
  document.removeEventListener('visibilitychange', onVisibilityFlush)
  window.removeEventListener('pagehide', onVisibilityFlush)
})
</script>

<template>
  <audio
    ref="audioRef"
    data-testid="global-audio"
    preload="metadata"
    @timeupdate="onTimeUpdate"
    @play="onPlay"
    @pause="onPause"
    @ended="onEnded"
  />
</template>

// src/components/AudioHost.tsx
import { useEffect, useRef } from 'react'

import { appendAppLog } from '@/lib/appLogStore'
import { syncMediaSession } from '@/lib/playback/mediaSession'
import { prefetchUpcoming } from '@/lib/playback/prefetchUpcoming'
import { createPlaybackTransport } from '@/lib/playback/playbackTransport'
import { resolvePlayableUrl } from '@/lib/playback/resolvePlayableUrl'
import { useCatalogStore } from '@/stores/catalog'
import { usePlayerStore } from '@/stores/player'

const PREFETCH_COUNT = 3

function createTransport(getAudio: () => HTMLAudioElement | null) {
  function resolveTrackForPrefetch(id: string) {
    const track = useCatalogStore.getState().snapshot.trackById.get(id)
    if (!track) return undefined
    return { id: track.id, path: track.path }
  }

  function schedulePrefetch() {
    const player = usePlayerStore.getState()
    void prefetchUpcoming(player.queue, player.currentIndex, {
      count: PREFETCH_COUNT,
      repeatMode: player.repeatMode,
      shuffle: player.shuffle,
      resolveTrack: resolveTrackForPrefetch,
      onTrackCached: (id) => useCatalogStore.getState().scheduleEnrichTrack(id),
    })
  }

  return createPlaybackTransport({
    getAudio,
    getCurrentId: () => usePlayerStore.getState().currentId,
    getQueueLength: () => usePlayerStore.getState().queue.length,
    getSeekTo: () => usePlayerStore.getState().seekTo,
    getPendingPlay: () => usePlayerStore.getState().pendingPlay,
    getRepeatMode: () => usePlayerStore.getState().repeatMode,
    clearSeekTo: () => {
      usePlayerStore.setState({ seekTo: null })
    },
    pause: () => usePlayerStore.getState().pause(),
    skip: () => usePlayerStore.getState().skip(),
    onEnded: () => usePlayerStore.getState().onEnded(),
    getTrack: (id) => {
      const track = useCatalogStore.getState().snapshot.trackById.get(id)
      if (!track) return undefined
      return { id: track.id, path: track.path }
    },
    setPlaying: (playing) => {
      usePlayerStore.setState({ playing })
    },
    clearPendingPlay: () => {
      usePlayerStore.setState({ pendingPlay: false })
    },
    flushPersist: () => usePlayerStore.getState().flushPersist(),
    setCurrentTime: (time) => {
      usePlayerStore.setState({ currentTime: time })
    },
    setDuration: (duration) => {
      usePlayerStore.setState({ duration })
    },
    syncMediaSession: () => {
      const player = usePlayerStore.getState()
      const track = player.currentId
        ? useCatalogStore.getState().snapshot.trackById.get(player.currentId)
        : undefined
      syncMediaSession(track, player)
    },
    schedulePrefetch,
    resolvePlayableUrl,
    appendAppLog: (message) => {
      void appendAppLog(message)
    },
    scheduleEnrichTrack: (id) => useCatalogStore.getState().scheduleEnrichTrack(id),
  })
}

export function AudioHost() {
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const transportRef = useRef<ReturnType<typeof createPlaybackTransport> | null>(null)
  if (transportRef.current == null) {
    transportRef.current = createTransport(() => audioRef.current)
  }
  const transport = transportRef.current

  const loadToken = usePlayerStore((s) => s.loadToken)
  const pendingPlay = usePlayerStore((s) => s.pendingPlay)
  const seekTo = usePlayerStore((s) => s.seekTo)
  const repeatMode = usePlayerStore((s) => s.repeatMode)
  const queue = usePlayerStore((s) => s.queue)
  const currentId = usePlayerStore((s) => s.currentId)
  const playing = usePlayerStore((s) => s.playing)
  const displayTitle = useCatalogStore((s) =>
    currentId ? (s.snapshot.trackById.get(currentId)?.displayTitle ?? null) : null,
  )
  const displayCover = useCatalogStore((s) =>
    currentId ? (s.snapshot.trackById.get(currentId)?.displayCover ?? null) : null,
  )

  useEffect(() => {
    void transport.loadCurrent()
  }, [loadToken, transport])

  useEffect(() => {
    transport.syncMediaSession()
  }, [currentId, playing, displayTitle, displayCover, transport])

  useEffect(() => {
    if (usePlayerStore.getState().currentId) transport.schedulePrefetch()
  }, [queue, transport])

  useEffect(() => {
    transport.onRepeatModeChange(repeatMode)
  }, [repeatMode, transport])

  useEffect(() => {
    transport.onPendingPlayChange(pendingPlay)
  }, [pendingPlay, transport])

  useEffect(() => {
    transport.onSeekToChange(seekTo)
  }, [seekTo, transport])

  useEffect(() => {
    function onVisibilityFlush() {
      usePlayerStore.getState().flushPersist()
    }

    transport.syncLoopFromRepeatMode()
    document.addEventListener('visibilitychange', onVisibilityFlush)
    window.addEventListener('pagehide', onVisibilityFlush)
    transport.syncMediaSession()

    return () => {
      document.removeEventListener('visibilitychange', onVisibilityFlush)
      window.removeEventListener('pagehide', onVisibilityFlush)
    }
  }, [transport])

  return (
    <audio
      ref={audioRef}
      data-testid="global-audio"
      preload="metadata"
      hidden
      onTimeUpdate={transport.onTimeUpdate}
      onPlay={transport.onPlay}
      onPause={transport.onPause}
      onEnded={transport.onEnded}
    />
  )
}
