// src/components/TrackList.tsx
import List from '@mui/material/List'

import { TrackListItem } from '@/components/TrackListItem'
import type { DisplayTrack } from '@/stores/catalog'

export type TrackListProps = {
  tracks: DisplayTrack[]
  currentId?: string | null
  onSelect?: (index: number) => void
  onPlayNext?: (id: string) => void
  onAddToQueue?: (id: string) => void
}

export function TrackList({
  tracks,
  currentId = null,
  onSelect,
  onPlayNext,
  onAddToQueue,
}: TrackListProps) {
  return (
    <List sx={{ bgcolor: 'transparent', py: 0 }}>
      {tracks.map((track, index) => (
        <TrackListItem
          key={track.id}
          track={track}
          active={currentId === track.id}
          onSelect={() => onSelect?.(index)}
          onPlayNext={() => onPlayNext?.(track.id)}
          onAddToQueue={() => onAddToQueue?.(track.id)}
        />
      ))}
    </List>
  )
}

// src/components/TrackList.vue
<script setup lang="ts">
import TrackListItem from '@/components/TrackListItem.vue'
import type { DisplayTrack } from '@/stores/catalog'

defineProps<{
  tracks: DisplayTrack[]
  currentId?: string | null
}>()

const emit = defineEmits<{
  select: [index: number]
  playNext: [id: string]
  addToQueue: [id: string]
}>()
</script>

<template>
  <v-list bg-color="transparent">
    <TrackListItem
      v-for="(track, index) in tracks"
      :key="track.id"
      :track="track"
      :active="currentId === track.id"
      @select="emit('select', index)"
      @play-next="emit('playNext', track.id)"
      @add-to-queue="emit('addToQueue', track.id)"
    />
  </v-list>
</template>
