// src/components/TrackListItem.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import CoverImg from '@/components/CoverImg.vue'
import { useTrackDownload } from '@/composables/useTrackDownload'
import { localizeAlbumName, localizeArtistName } from '@/lib/catalog/displayLabels'
import type { DisplayTrack } from '@/stores/catalog'
import { usePlayerStore } from '@/stores/player'

const props = withDefaults(
  defineProps<{
    track: DisplayTrack
    active?: boolean
    /** playback = Play next / Add to queue; queue = Remove from queue */
    actions?: 'playback' | 'queue' | 'none'
  }>(),
  { actions: 'playback' },
)

const emit = defineEmits<{
  select: []
  'play-next': []
  'add-to-queue': []
  remove: []
}>()

const { t } = useI18n()
const player = usePlayerStore()
const { downloading } = useTrackDownload(() => props.track)
const coverBusy = computed(() => downloading.value && player.currentId === props.track.id)
</script>

<template>
  <v-list-item :active="active" rounded="lg" class="track-row" @click="emit('select')">
    <template #prepend>
      <v-avatar rounded="lg" size="40" class="me-3">
        <CoverImg
          v-if="track.displayCover || coverBusy"
          :src="track.displayCover"
          :downloading="coverBusy"
        />
        <v-icon v-else icon="mdi-music" />
      </v-avatar>
    </template>
    <v-list-item-title>{{ track.displayTitle }}</v-list-item-title>
    <v-list-item-subtitle>
      {{ localizeArtistName(track.displayArtist, t) }}
      <template v-if="track.displayAlbum">
        · {{ localizeAlbumName(track.displayAlbum, t) }}
      </template>
    </v-list-item-subtitle>
    <template v-if="actions !== 'none'" #append>
      <v-menu location="bottom end" transition="fade-transition">
        <template #activator="{ props: menuProps }">
          <v-btn
            v-bind="menuProps"
            data-testid="track-actions"
            icon="mdi-dots-vertical"
            variant="text"
            size="small"
            @click.stop
            @pointerdown.stop
          />
        </template>
        <v-list density="compact" min-width="180">
          <template v-if="actions === 'playback'">
            <v-list-item
              data-testid="track-play-next"
              prepend-icon="mdi-playlist-play"
              :title="t('player.playNext')"
              @click="emit('play-next')"
            />
            <v-list-item
              data-testid="track-add-to-queue"
              prepend-icon="mdi-playlist-plus"
              :title="t('player.addToQueue')"
              @click="emit('add-to-queue')"
            />
          </template>
          <v-list-item
            v-else-if="actions === 'queue'"
            data-testid="track-remove"
            prepend-icon="mdi-playlist-remove"
            :title="t('player.removeFromQueue')"
            @click="emit('remove')"
          />
        </v-list>
      </v-menu>
    </template>
  </v-list-item>
</template>

<style scoped>
.track-row {
  transition: background-color 0.2s ease;
}
</style>

// src/components/TrackListItem.tsx
import { useState, type MouseEvent, type PointerEvent } from 'react'
import Avatar from '@mui/material/Avatar'
import IconButton from '@mui/material/IconButton'
import ListItemButton from '@mui/material/ListItemButton'
import ListItemIcon from '@mui/material/ListItemIcon'
import ListItemText from '@mui/material/ListItemText'
import Menu from '@mui/material/Menu'
import MenuItem from '@mui/material/MenuItem'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import MusicNoteIcon from '@mui/icons-material/MusicNote'
import PlaylistAddIcon from '@mui/icons-material/PlaylistAdd'
import PlaylistPlayIcon from '@mui/icons-material/PlaylistPlay'
import PlaylistRemoveIcon from '@mui/icons-material/PlaylistRemove'
import { useTranslation } from 'react-i18next'

import { CoverImg } from '@/components/CoverImg'
import { useTrackDownload } from '@/hooks/useTrackDownload'
import { localizeAlbumName, localizeArtistName } from '@/lib/catalog/displayLabels'
import type { DisplayTrack } from '@/stores/catalog'
import { usePlayerStore } from '@/stores/player'

export type TrackListItemProps = {
  track: DisplayTrack
  active?: boolean
  /** playback = Play next / Add to queue; queue = Remove from queue */
  actions?: 'playback' | 'queue' | 'none'
  onSelect?: () => void
  onPlayNext?: () => void
  onAddToQueue?: () => void
  onRemove?: () => void
}

export function TrackListItem({
  track,
  active = false,
  actions = 'playback',
  onSelect,
  onPlayNext,
  onAddToQueue,
  onRemove,
}: TrackListItemProps) {
  const { t } = useTranslation()
  const currentId = usePlayerStore((s) => s.currentId)
  const { downloading } = useTrackDownload(track)
  const coverBusy = downloading && currentId === track.id

  const [menuAnchor, setMenuAnchor] = useState<HTMLElement | null>(null)
  const menuOpen = Boolean(menuAnchor)

  function openMenu(event: MouseEvent<HTMLElement>) {
    event.stopPropagation()
    setMenuAnchor(event.currentTarget)
  }

  function stopPointerDown(event: PointerEvent) {
    event.stopPropagation()
  }

  function closeMenu() {
    setMenuAnchor(null)
  }

  const artist = localizeArtistName(track.displayArtist, t)
  const subtitle = track.displayAlbum
    ? `${artist} · ${localizeAlbumName(track.displayAlbum, t)}`
    : artist

  return (
    <ListItemButton
      selected={active}
      className="track-row"
      onClick={() => onSelect?.()}
      sx={{ borderRadius: 2, transition: 'background-color 0.2s ease' }}
    >
      <Avatar variant="rounded" sx={{ width: 40, height: 40, mr: 1.5, bgcolor: 'action.hover' }}>
        {track.displayCover || coverBusy ? (
          <CoverImg src={track.displayCover} downloading={coverBusy} />
        ) : (
          <MusicNoteIcon fontSize="small" />
        )}
      </Avatar>
      <ListItemText
        primary={track.displayTitle}
        secondary={subtitle}
        slotProps={{
          primary: { noWrap: true },
          secondary: { noWrap: true },
        }}
      />
      {actions !== 'none' ? (
        <>
          <IconButton
            data-testid="track-actions"
            size="small"
            edge="end"
            aria-label={t('nav.more')}
            onClick={openMenu}
            onPointerDown={stopPointerDown}
          >
            <MoreVertIcon fontSize="small" />
          </IconButton>
          <Menu
            anchorEl={menuAnchor}
            open={menuOpen}
            onClose={closeMenu}
            anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
            transformOrigin={{ vertical: 'top', horizontal: 'right' }}
            transitionDuration={150}
            slotProps={{ list: { dense: true, sx: { minWidth: 180 } } }}
          >
            {actions === 'playback' ? (
              <>
                <MenuItem
                  data-testid="track-play-next"
                  onClick={() => {
                    closeMenu()
                    onPlayNext?.()
                  }}
                >
                  <ListItemIcon>
                    <PlaylistPlayIcon fontSize="small" />
                  </ListItemIcon>
                  {t('player.playNext')}
                </MenuItem>
                <MenuItem
                  data-testid="track-add-to-queue"
                  onClick={() => {
                    closeMenu()
                    onAddToQueue?.()
                  }}
                >
                  <ListItemIcon>
                    <PlaylistAddIcon fontSize="small" />
                  </ListItemIcon>
                  {t('player.addToQueue')}
                </MenuItem>
              </>
            ) : (
              <MenuItem
                data-testid="track-remove"
                onClick={() => {
                  closeMenu()
                  onRemove?.()
                }}
              >
                <ListItemIcon>
                  <PlaylistRemoveIcon fontSize="small" />
                </ListItemIcon>
                {t('player.removeFromQueue')}
              </MenuItem>
            )}
          </Menu>
        </>
      ) : null}
    </ListItemButton>
  )
}
